### ISSUE TITLE
Documentation (README) give false hope about documentMiddleware.

### ISSUE THREAD

**Issue by ztec** [prisma/graphql-middleware#10]
As explain here : https://github.com/prismagraphql/graphql-yoga/issues/314 `documentMiddleware` is not yet available. What do you think of removing it from README.md and only document `middleware` parameter of Graphql-Yoga ?

**Comment by namnm** [comment]
Yeah, I still wonder why dont we just put the `documentMiddleware` in this package instead of introducing the `yoga` or whatever, any reason that `documentMiddleware` can not be put here?
