### ISSUE TITLE
Provide function name for 'resolve' parameter

### ISSUE THREAD

**Issue by checkmatez** [prisma/graphql-middleware#23]
Hello, thanks for the package!
I am trying to setup logging with middleware. It would be nice to be able to log name of actual resolver function like so:
```
const loggingMiddleware = async (
  resolve,
  root,
  args,
  context,
  info
) => {
  console.log(`${resolve.name} args:`, args)
  const result = await resolve(root, args, context, info)
  console.log(`${resolve.name} result:`, result)
  return result
}
```
and I expect it to log: "getUser args: {} ".
I think it would be required for resolvers to be an actual function and not anonymous, but I am ok with it as long as I can map log entry to the resolver file.

**Comment by maticzav** [comment]
Hey @checkmatez 👋!

What an interesting idea! I usually tackle such problems using `info` argument that we gain from each resolver. Have you seen its implementation yet?

```ts
interface GraphQLResolveInfo {
  fieldName: string;
  fieldNodes: FieldNode[];
  returnType: GraphQLOutputType;
  parentType: GraphQLCompositeType;
  path: ResponsePath;
  schema: GraphQLSchema;
  fragments: { [fragmentName: string]: FragmentDefinitionNode };
  rootValue: any;
  operation: OperationDefinitionNode;
  variableValues: { [variableName: string]: any };
}
```

The exciting part to you will probably be `fieldName` field. You can use it to identify a field name in a type. Furthermore, you could also do something a bit more complex and include type name in the log. This way you could print more detailed logs such as `Query.apples: Foobar qux did this` or `Apple.id: did that`. To derive type name as well, you'll use `parentType` field and its property `name`.

Like this;

```ts
const logger = async (resolve, parent, args, ctx, info) => {
  console.log(`${info.parentType.name}.${info.fieldName}: logged this!`)
  return resolve()
}
```

I hope this solves your problem. Let me know if you need any help implementing it! 🙂

**Comment by checkmatez** [comment]
Thanks for the suggestion, I'll try that approach.
In general, yes a I know about `info` but I try to avoid it, since it is not obvious how to work with it. And yes, I've read [fantastic article](https://www.prisma.io/blog/graphql-server-basics-demystifying-the-info-argument-in-graphql-resolvers-6f26249f613a/) about info arg like three times but it is still feels like more of implementation detail than an actual api you have to learn.

**Comment by maticzav** [comment]
Nice! I am not sure about the second part though. What do you mean with API vs implementation detail? `info` serves as a link to your schema declaration. I would even dare say that it's the only necessary one. Don't hold me for a word here as I haven't tried it yet but I think you could derive `parent`, `args`, not `ctx` I believe, from it. 

I would also encourage you to check out type definitions in `graphql-js` or `graphql-tools`. The first one has a barebones Flow implementation which isn't always the best option for me; the second one though gives you a nice flow of types if you are using VSCode. Just click around to find definitions. I have spent numerous amount of hours just going through the core - trust me, it's super fun!

https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L792

https://github.com/apollographql/graphql-tools

**Comment by maticzav** [comment]
I'll close this issue as it seems to be resolved.
