### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by brandondoran** [prisma/graphql-middleware#24]
I'm seeing a noticeable performance hit when using graphql-middleware. I was hoping to use middleware to log resolver errors. Before going all in, I added a very simple middleware and deployed to production to test under load:

```javascript
export const errorLogger = async (resolve, root, args, context, info) => {
  try {
    return await resolve(root, args, context, info);
  } catch (err) {
    // TODO: log errors
    throw err;
  }
};
```

Instrumentation showed time spent in Node doubled and overall response time was 10-15% slower.

The server is apollo-server-express.  I've previously added [schema directives](https://www.apollographql.com/docs/graphql-tools/schema-directives.html) to add some instrumentation to resolvers and saw no performances hit with those.

I really like the idea of graphql-middleware for something like logging/error reporting but the extra overhead. Any ideas on how to optimize?

**Comment by brandondoran** [comment]
I'm realizing now that the middleware is called on every field not just async ones and this is probably the main contributor this issue.

**Comment by brandondoran** [comment]
I've implemented logic in my middleware to not blindly use async/await for all resolvers and performance is 💯.  So I will close this.

I didn't not see it originally but this issue is basically what https://github.com/prisma/graphql-middleware/pull/14 is talking about.  I think would indeed but good to have a disclaimer in the readme.

**Comment by AbdelrhmanAbdelhamed** [comment]
> I've implemented logic in my middleware to not blindly use async/await for all resolvers and performance is 💯. So I will close this.
> 
> I didn't not see it originally but this issue is basically what #14 is talking about. I think would indeed but good to have a disclaimer in the readme.

Hello @brandondoran Can you clarify more on the solution? perhaps using an example of how the middleware looks before and after for both cases. Thank you
