### ISSUE TITLE
Allow applyMiddlewareToField to spread extra properties or add specific key for extra metadata

### ISSUE THREAD

**Issue by JCMais** [prisma/graphql-middleware#25]
Currently `applyMiddlewareToField` only spreads the properties it wants to:

https://github.com/prisma/graphql-middleware/blob/500925ade884a025cb6eb2ba99672c4f4a52b13c/src/applicator.ts#L41-L84

It would be really useful if extra properties were also added to the final field definition, that way we could declare some custom properties that could be used directly in the middlewares.

For instance, we could have a middleware added to all mutations, but that only does something to mutations that have a specific flag.
```
// ...
const resolvers = {
  // ...
  Mutation: {
    // ...
    DoSomething: {
      flags: [FLAGS.SPECIFIC_FLAG],
      resolve: async (root, args, context, info)=> {
        // ...
      },
    }
  },
}
```

then on the middleware:
```
const customValidation = {
  async Mutation(resolve, root, args, context, info) {
    // use info to get the _typeConfig of the mutation being executed
    const mutationConfig = ...;
    if (mutationConfig.flags && mutationConfig.flags.includes(FLAGS.SPECIFIC_FLAG)) {
      // Do something
    }
  }
}
```

I'm asking for that because I'm migrating some code that uses [graphql-add-middleware](https://github.com/alekbarszczewski/graphql-add-middleware) to use `graphql-middleware` instead.

I'm going to write a post about validations with `graphql-middleware`, but for it to work I need this "feature".

Thoughts?

I can get some time to work on that if it's acceptable.

`addResolveFunctionsToSchema` from `graphql-tools` does spreads all other properties, so it's not a problem.

See related code there:
https://github.com/apollographql/graphql-tools/blob/3b77c2071e4b2328b1a4c4471c61d4ad93a6ae57/src/generate/addResolveFunctionsToSchema.ts#L121

https://github.com/apollographql/graphql-tools/blob/3b77c2071e4b2328b1a4c4471c61d4ad93a6ae57/src/generate/addResolveFunctionsToSchema.ts#L140-L147

**Comment by maticzav** [comment]
What an exciting idea @JCMais! Could you make a PR with the implementation of it? I could help you if you wish. 🙂 

One question I have though; how would you access extra fields from within the resolver?

**Comment by JCMais** [comment]
@maticzav Thanks! I will work on that this week, seems simple, since It's just necessary to spread `field` above, but any doubts I will ask here.

About your last question, we can access those extra fields, and any other field, like this (following the example schema above):
```
info.schema.getMutationType().getFields()[info.fieldName].flags
```

**Comment by maticzav** [comment]
I see. Is this the desired usage? Maybe we should make it more easily accessible if that’s the case.

**Comment by JCMais** [comment]
hm, I don't think you guys should have full support for that use case, since it kinda of is more dependent on thirdy libraries (It depends on graphql-tools and graphql-js itself passing extra fields forward, which they do currently, leaving them acessible via the info argument).

The idea is just to allow for that, but not have it like a supported usage or anything like that.

I'm planning on making a post about it after I get the PR merged, showing how it works and how it can be done, but I was already going to put a notice that this is dependent on some internals that can change in future versions. 😄

**Comment by JCMais** [comment]
@marktani I've just opened a PR for this: https://github.com/prisma/graphql-middleware/pull/26

**Comment by JCMais** [comment]
@maticzav btw, I just published the post I mentioned above: https://medium.com/@jonathancardoso/graphql-mutation-arguments-validation-with-yup-using-graphql-middleware-645822fb748
