### ISSUE TITLE
Question: wrap all top-level queries / mutations only

### ISSUE THREAD

**Issue by dwelch2344** [prisma/graphql-middleware#78]
Hey all, trying to figure out if I'm approaching this wrong or just not understanding. So, what I'd like to do is put a simple tracing middleware around any "top level" query. I.e. the request comes in and they ask for `PersonA` and `PersonB` query. 

I've got one that runs, and I can filter out decently well by only measuring if `parent` is null, which seems to work. But the downside is that it's making my introspection query SUPER slow – proabbly because it's hitting every prop and we have a huuuge schema which is split into multiple files and stitched together. Also, we're on lambda,  so we recompile this on every invocation (at least locally) so our dev cycles are suffering. 

I'm wondering: is there some easy way to say `wrap Query.* and Mutation.*` but not anything deeper? I saw #13 and looked at the `applyMiddlewareToDeclaredResolvers` but it doesn't seem to have much impact.

Thoughts? Am I missing something simple?

**Comment by maticzav** [comment]
Hey @dwelch2344 👋,

Have you tried scoping the range of `middleware`? You can do this by specifying `types` or `fields` it should apply to. Try the following;

```ts
const middleware = {
  Query: middleware,
  Mutation: middleware,
}

const schema = applyMiddleware(schema, middleware)
```

**Comment by dwelch2344** [comment]
Ah, that's brilliant. No, I saw that somewhere in the docs / examples but couldn't really grok it. I'll give that a whirl and compare :) thanks

**Comment by ghirlekar** [comment]
Is it possible to apply a middleware to all fields except one?
I want to apply my authorization middleware to all fields except one root level query that generates JWTs; else no one could ever login.

**Comment by maticzav** [comment]
Hey @ghirlekar 👋,

That’s an interesting question! Unfortunately, there’s no middleware function which would explicitly omit application of middleware to a specific field. However, you could use `info` parameter and determine whether the middleware should or shouldn't run.

`info` parameter stores a `fieldName` and also `parentType` parameter which you could combine to determine execution.

Let me know how implementation went! 🙂

**Comment by ghirlekar** [comment]
@maticzav, I elected to use graphql-shield instead of rolling my own middleware. The fallbackRule option works perfectly for this kinda task. 

I apologize that this comment is extremely off-topic in this issue, but in case anyone is interested, this is the way I've setup my authorization rules.

```javascript
const { shield, rule, and, or, not, allow } = require('graphql-shield');

// Authorization rules
const deny401 = rule()(() => new Error('401 Unauthorized'));
const deny403 = rule()(() => new Error('403 Forbidden'));
const isAuthenticated = or(rule()((parent, args, { req }) => {
  return req.session.id != null;
}), deny401);
const isAdmin = and(isAuthenticated, rule()((parent, args, { req }) => {
  return req.session.roles.includes('admin'); 
}));
const isSales = and(isAuthenticated, rule()((parent, args, { req }) => {
  return req.session.roles.includes('admin') || req.session.roles.includes('sales');
}));
const isInvoiceLocked = and(isAuthenticated, rule()((parent, args, ctx) => {
  return ctx.is_invoice_locked;
}));

module.exports = shield({
  RootQuery: {
    schema_version: allow,
  },
  RootMutation: {
    login: allow,
    invoice_create: or(isSales, deny403),
    invoice_update: or(and(isSales, or(not(isInvoiceLocked), isAdmin)), deny403),
    invoice_delete: or(isSales, deny403),
    sales_order_create: or(isSales, deny403),
    sales_order_update: or(and(isSales, or(not(isInvoiceLocked), isAdmin)), deny403),
    sales_order_delete: or(isSales, deny403),
  }
}, { fallbackRule: isAuthenticated, graphiql: true });
```

@maticzav, thanks for your wonderful graphql-shield module. It's very well structured and has saved me so much time. I am very grateful for your efforts.

**Comment by maticzav** [comment]
@ghirlekar thank you so much for such fantastic feedback! :green_heart: I am genuinely happy that it's working out for you. 

Besides that, thanks for sharing the code. I am sure it will be of good use to others with a similar issue 🙂

**Comment by Abhijeetjaiswalit** [comment]
@maticzav i didn't get scoping the range of `middleware`
`const middleware = {
  Query: middleware,
  Mutation: middleware,
}`

i'm doing something like this =>
`
const executableSchema = makeExecutableSchema({
  typeDefs: schema,
  resolvers: {
    ...resolvers,
    JSON: GraphQLJSON
  },
  schemaDirectives: {
    auth: AuthDirective
  }
});
const schemaWithMiddleware = applyMiddleware(
  executableSchema,
  logInputMiddleware,
  logResultMiddleware
);
`

so my problem is, i'm not getting how i will be able to scope `logInputMiddleware` and `logInputMiddleware` for Mutation(for example: saveChild) only. not for every types/fields
const schema = applyMiddleware(schema, middleware).
right now, its checking for every field/type.

**Comment by maticzav** [comment]
@Abhijeetjaiswalit 

```ts
const executableSchema = makeExecutableSchema({
  typeDefs: schema,
  resolvers: { ...resolvers, JSON: GraphQLJSON },
  schemaDirectives: { auth: AuthDirective },
})

const schemaWithMiddleware = applyMiddleware(
  executableSchema,
  {
    Query: logInputMiddleware,
    Mutation: logInputMiddleware,
  },
  {
    Query: {
       user: logResultMiddleware,
    },
  },
)
```
