### ISSUE TITLE
apply multiple middelwares to executable schema 

### ISSUE THREAD

**Issue by gastonovic** [prisma/graphql-middleware#87]
Hi, I'm trying to add multiple middlewares to a resolver function (for authorization purposes) 
the problem is that when I try to do that like this :
`const middlewares = [bodyParser, passport.authenticate('jwt', { session : false })];`
`const schemaWithMiddleware = applyMiddleware(schema, middlewares);`
I get this error : 
`/graphql-middleware/dist/validation.js:24`
           ` throw new MiddlewareError("Type " + type + " exists in middleware but is missing in Schema.");`

`Error: Type 0 exists in middleware but is missing in Schema.`

**Comment by maticzav** [comment]
You should wrap `passport` in middleware function.`middlewares` are not meant to support express-middleware.
